/**
 * テーマ別テキストマッピング
 */

import { Theme } from '../types';

export const TEXT_MAPPING = {
    kids: {
        // モード名
        STANDARD: 'ふつうのけいさん',
        DATE: '日づけ',
        UNIT: 'たんい',
        ZODIAC: '十二支',
        FORTUNE: 'うらない',
        CART: 'カート',

        // 電卓ボタン
        CLEAR: 'C',
        NEGATE: '+/-',
        PERCENT: '%',
        POWER: 'x² べき乗',
        FRACTION: '📊 分数',
        DIVIDE: '÷',
        MULTIPLY: '×',
        SUBTRACT: '-',
        ADD: '+',
        EQUALS: '=',
        DECIMAL: '.',
        BACKSPACE: '⌫',

        // 日付計算タブ
        DATE_BASIC: 'きほん',
        DATE_AGE: 'ねんれい',
        DATE_INFO: 'ひづけ',
        DATE_ANNIVERSARY: 'きねんび',
        DATE_TRIVIA: 'きょうはなんのひ',
        DATE_CULTURE: 'にほんのぶんか',
        DATE_CALENDAR: 'カレンダー',
        DATE_ADVANCED: 'こうど',
        DATE_TIMELINE: 'たいむらいん',
        DATE_HISTORY: 'れきし',
        DATE_COUNTDOWN: 'かうんとだうん',
        DATE_YEARLY: 'ねんかん',
        DATE_WEEKLY: 'しゅうかん',
        DATE_RANGE: 'はんい',
        DATE_ANNIVERSARY_LIST: 'きねんびリスト',
        DATE_EXPORT: 'エクスポート',
        DATE_BASIC_TITLE: 'きほんのけいさん',
        DATE_ADD: 'たす',
        DATE_SUBTRACT: 'ひく',
        DATE_DIFFERENCE: 'ちがい',
        DATE_START_DATE: 'はじめのひづけ',
        DATE_AMOUNT: 'たす・ひく りょう',
        DATE_UNIT_DAYS: 'にち',
        DATE_SLIDER: 'スライダーでかんたんにちょうせい',
        DATE_CALCULATE: 'けいさんする',
        DATE_HISTORY_VIEW: 'けいさんれきしをみる',
        UNIT_TITLE: 'たんいへんかん',
        UNIT_CATEGORY: 'たんいのしゅるい',
        UNIT_INPUT: 'すうじをにゅうりょく',
        UNIT_FROM: 'もとのたんい',
        UNIT_TO: 'へんかんさきのたんい',
        UNIT_SELECT: 'たんいをえらんでね',
        UNIT_CONVERT: 'へんかんする',
        ZODIAC_TITLE: '今年の干支',
        ZODIAC_BIRTH_YEAR: 'うまれた年 (西暦)',
        ZODIAC_SEARCH: '十二支をしらべる',
        FORTUNE_BIRTH_DATE: 'うまれたひをいれてね',
        FORTUNE_TELL: 'うらなう！',
        FORTUNE_DIAGNOSIS_TITLE: 'そうごううんせいしんだん',
        FORTUNE_DIAGNOSIS_DESC: 'うえにうまれたひをいれて「うらなう！」ボタンをおしてね',
        CART_TITLE: 'ショッピングカート',
        CART_ADD_ITEM: 'アイテムを追加',
        CART_ITEM_NAME: '商品名',
        CART_ITEM_PRICE: '価格',
        CART_EMPTY: 'カートは空です',

        // 十二支タブ
        ZODIAC_MAIN: 'かんたん',
        ZODIAC_AGE: 'ねんれい',
        ZODIAC_COMPATIBILITY: 'あいしょう',
        ZODIAC_INFO: 'おべんきょう',
        ZODIAC_QUIZ: 'クイズ',

        // 占いタブ
        FORTUNE_DIAGNOSIS: 'そうごう',
        FORTUNE_CONSTELLATION: 'せいざ',
        FORTUNE_NUMEROLOGY: 'すうじ',
        FORTUNE_WEEKDAY: 'ようび',
        FORTUNE_OMIKUJI: 'おみくじ',
        FORTUNE_COMPATIBILITY: 'あいしょう',
        FORTUNE_MONTHLY: 'つきうらない',
        FORTUNE_BIORHYTHM: 'バイオリズム',
        FORTUNE_POWERSTONE: 'パワーストーン',
        FORTUNE_WISH: 'ねがいごと',
        FORTUNE_LUCKYTIME: 'ラッキータイム',
        FORTUNE_TAROT: 'タロット',
        FORTUNE_COLOR: 'いろうらない',
        FORTUNE_NINESTAR: 'きゅうせい',
        FORTUNE_CHART: 'うんせいグラフ',
        FORTUNE_FOURPILLARS: 'しちゅう',
        FORTUNE_DREAM: 'ゆめうらない',

        // カートタブ
        CART_LIST: '📝 リスト',
        CART_CALC: '💰 けいさん',
        CART_HISTORY: '📋 れきし',

        // その他
        CALCULATE: 'けいさん',
        RESULT: 'けっか',
        HISTORY: 'れきし',
        EXPORT: 'エクスポート',
        IMPORT: 'インポート',
        DELETE: 'けす',
        CLEAR_ALL: 'すべて削除',
        CLOSE: 'とじる',
        HELP: 'ヘルプ',
        BLOCKLY: '🧩 ブロック',

        // 日付計算の追加テキスト
        DATE_FIRST_DATE: '1つめのひづけ',
        DATE_SECOND_DATE: '2つめのひづけ',
        DATE_DIFFERENCE_CALC: 'ちがいをけいさん',
        DATE_AGE_TITLE: 'ねんれい・がくねんけいさん',
        DATE_BIRTH_DATE: 'うまれたひ',
        DATE_CALC_AGE: 'ねんれいをけいさん',
        DATE_RESULT: 'けっか',
        DATE_AGE_DETAILS: 'ねんれいのくわしいじょうほう',
        DATE_YEAR: 'ねん',
        DATE_MONTH: 'げつ',
        DATE_DAY: 'にち',
        DATE_YEAR_PROGRESS: 'ねんの%けいか',
        DATE_MONTH_PROGRESS: 'げつの%けいか',
        DATE_INFO_TITLE: 'ひづけのじょうほう',
        DATE_INFO_DATE: 'ひづけ',
        DATE_INFO_SEARCH: 'じょうほうをしらべる',
        DATE_INFO_RESULT: 'じょうほう',
        DATE_ANNIVERSARY_TITLE: 'きねんびまでのにちすう',
        DATE_ANNIVERSARY_DATE: 'きねんびのひづけ',
        DATE_ANNIVERSARY_CALC: 'きねんびまでのにちすうをけいさん',
        DATE_ANNIVERSARY_NAME: 'きねんびのなまえ',
        DATE_ANNIVERSARY_TYPE: 'しゅるい',
        DATE_ANNIVERSARY_BIRTHDAY: 'たんじょうび',
        DATE_ANNIVERSARY_ANNIVERSARY: 'きねんび',
        DATE_ANNIVERSARY_EVENT: 'イベント',
        DATE_ANNIVERSARY_CUSTOM: 'カスタム',
        DATE_ANNIVERSARY_REGISTER: 'とうろくする',
        DATE_ANNIVERSARY_REGISTER_TITLE: 'きねんびをとうろく',
        DATE_ANNIVERSARY_NAME_LABEL: 'なまえ',
        DATE_ANNIVERSARY_LIST_TITLE: 'きねんびリスト',
        DATE_ANNIVERSARY_CLEAR_ALL: 'ぜんぶけす',
        DATE_ANNIVERSARY_EMPTY: 'きねんびはまだありません',
        DATE_HISTORY_EMPTY: 'れきしがありません',
        DATE_ANNIVERSARY_DAYS_UNTIL: 'あと %にち',
        DATE_ANNIVERSARY_TODAY: 'きょうです！',
        DATE_ANNIVERSARY_DAYS_PAST: '%にちすぎました',
        DATE_IMPORT_CSV: 'CSVからインポート',
        DATE_IMPORT_JSON: 'JSONからインポート',
        DATE_IMPORT_SUCCESS: '%件の記念日をインポートしました',
        DATE_IMPORT_ERROR: 'インポートに失敗しました: %',
        DATE_HISTORY_IMPORT_SUCCESS: '%件の履歴をインポートしました',

        // 単位変換の追加テキスト
        UNIT_CATEGORY_LENGTH: 'ながさ',
        UNIT_CATEGORY_WEIGHT: 'おもさ',
        UNIT_CATEGORY_VOLUME: 'かさ',
        UNIT_CATEGORY_TIME: 'じかん',
        UNIT_CATEGORY_TEMPERATURE: 'おんど',
        UNIT_CATEGORY_CURRENCY: 'おかね',
        UNIT_NUMBER: 'すうじ',

        // 十二支の追加テキスト
        ZODIAC_YEARS_PEOPLE: '%年 の人たち',
        ZODIAC_CURRENT_AGE: '→ いま %さい',

        // カートの追加テキスト
        CART_ITEMS: 'カートのアイテム',
        CART_ADD_ITEM_PROMPT: 'カートにアイテムを追加してください',
        CART_HISTORY_TITLE: 'カートのれきし',
        CART_HISTORY_EMPTY: 'れきしがありません',
        CART_SUBTOTAL: '小計',
        CART_DISCOUNT: '割引',
        CART_TAX: '消費税',
        CART_TAX_RATE: 'しょうひぜいりつ',
        CART_SETTINGS: 'けいさんせってい',
        CART_TOTAL: '合計',
        CART_ADD: '追加',
        CART_QUANTITY: '数量',

        // ウェルカムメッセージ
        WELCOME_TITLE: 'けいさんノートへようこそ！',
        WELCOME_DESC1: 'ひだりのでんたくで、けいさんしてみよう',
        WELCOME_DESC2: 'けっかがマグネットになって、こっちにでてくるよ！',

        // 日付単位
        DATE_UNIT_DAYS_TEXT: 'にち',
        DATE_UNIT_WEEKS_TEXT: 'しゅう',
        DATE_UNIT_MONTHS_TEXT: 'げつ',
        DATE_UNIT_YEARS_TEXT: 'ねん',
        DATE_AGE_YEARS: 'さい',
        DATE_AGE_MONTHS: 'かげつ',
        DATE_AGE_DAYS: 'にち',
        DATE_AGE_TOTAL: 'ぜんぶで',
        DATE_BORN: 'うまれ',
        DATE_NOW: 'いま',

        // 日付計算結果
        DATE_EVENT_DAYS_UNTIL: 'イベントまでのにちすう',
        DATE_WEEK_POSITION: 'しゅうのなんにちめか',

        // エラーメッセージ
        ERROR_INVALID_YEAR: 'せいかくな年をいれてね',
        ERROR_INVALID_YEAR_RANGE: '1から9999のねんをいれてね',
        ERROR_INVALID_AGE: '0から125のねんれいをいれてね',
        ERROR_INVALID_DATE: 'せいかくなひづけをにゅうりょくしてね',
        ERROR_INVALID_NUMBER: 'せいかくなすうじをにゅうりょくしてね',
        ERROR_QUIZ_WRONG: 'ざんねん！もういちどチャレンジ！',
        ERROR_NAME_DATE_REQUIRED: 'なまえとひづけをにゅうりょくしてね',

        // Canvas
        CANVAS_SELECTED: 'この マグネット をせんたくちゅう',
        CANVAS_GROUP: 'グループか',
        CANVAS_UNGROUP: 'グループかいじょ',
        CANVAS_DELETE: 'けす',
        CANVAS_SELECT_ALL: 'ぜんぶ',

        // CBlock
        CBLOCK_MEMO_WRITE: 'メモをかく',
        CBLOCK_DELETE: 'マグネットをけす',
        CBLOCK_DELETE_CONFIRM: 'このマグネットをけしますか？',
        CBLOCK_MEMO_PLACEHOLDER: 'メモをかいてね (Ctrl+Enterでほぞん、Escでキャンセル)',
    },
    business: {
        // モード名
        STANDARD: '標準計算',
        DATE: '日付計算',
        UNIT: '単位変換',
        ZODIAC: '干支',
        FORTUNE: '占い',
        CART: 'ショッピングカート',

        // 電卓ボタン
        CLEAR: 'C',
        NEGATE: '+/-',
        PERCENT: '%',
        POWER: 'x² べき乗',
        FRACTION: '📊 分数',
        DIVIDE: '÷',
        MULTIPLY: '×',
        SUBTRACT: '-',
        ADD: '+',
        EQUALS: '=',
        DECIMAL: '.',
        BACKSPACE: '⌫',

        // 日付計算タブ
        DATE_BASIC: '基本',
        DATE_AGE: '年齢',
        DATE_INFO: '日付情報',
        DATE_ANNIVERSARY: '記念日',
        DATE_TRIVIA: '今日は？',
        DATE_CULTURE: '日本の文化',
        DATE_CALENDAR: 'カレンダー',
        DATE_ADVANCED: '高度',
        DATE_TIMELINE: 'タイムライン',
        DATE_HISTORY: '履歴',
        DATE_COUNTDOWN: 'カウントダウン',
        DATE_YEARLY: '年間カレンダー',
        DATE_WEEKLY: '週間カレンダー',
        DATE_RANGE: '範囲',
        DATE_ANNIVERSARY_LIST: '記念日リスト',
        DATE_EXPORT: 'エクスポート',
        DATE_BASIC_TITLE: '基本計算',
        DATE_ADD: '加算',
        DATE_SUBTRACT: '減算',
        DATE_DIFFERENCE: '差分',
        DATE_START_DATE: '開始日付',
        DATE_AMOUNT: '加減算量',
        DATE_UNIT_DAYS: '日',
        DATE_SLIDER: 'スライダーで調整',
        DATE_CALCULATE: '計算',
        DATE_HISTORY_VIEW: '計算履歴を表示',
        UNIT_TITLE: '単位変換',
        UNIT_CATEGORY: '単位の種類',
        UNIT_INPUT: '数値を入力',
        UNIT_FROM: '変換元の単位',
        UNIT_TO: '変換先の単位',
        UNIT_SELECT: '単位を選択',
        UNIT_CONVERT: '変換',
        ZODIAC_TITLE: '今年の干支',
        ZODIAC_BIRTH_YEAR: '生年 (西暦)',
        ZODIAC_SEARCH: '干支を調べる',
        FORTUNE_BIRTH_DATE: '生年月日を入力',
        FORTUNE_TELL: '占う',
        FORTUNE_DIAGNOSIS_TITLE: '総合運勢診断',
        FORTUNE_DIAGNOSIS_DESC: '上記に生年月日を入力して「占う」ボタンを押してください',
        CART_TITLE: 'ショッピングカート',
        CART_ADD_ITEM: 'アイテムを追加',
        CART_ITEM_NAME: '商品名',
        CART_ITEM_PRICE: '価格',
        CART_EMPTY: 'カートは空です',

        // 十二支タブ
        ZODIAC_MAIN: '簡単',
        ZODIAC_AGE: '年齢',
        ZODIAC_COMPATIBILITY: '相性',
        ZODIAC_INFO: '学習',
        ZODIAC_QUIZ: 'クイズ',

        // 占いタブ
        FORTUNE_DIAGNOSIS: '総合',
        FORTUNE_CONSTELLATION: '星座',
        FORTUNE_NUMEROLOGY: '数秘術',
        FORTUNE_WEEKDAY: '曜日',
        FORTUNE_OMIKUJI: 'おみくじ',
        FORTUNE_COMPATIBILITY: '相性',
        FORTUNE_MONTHLY: '月占い',
        FORTUNE_BIORHYTHM: 'バイオリズム',
        FORTUNE_POWERSTONE: 'パワーストーン',
        FORTUNE_WISH: '願い事',
        FORTUNE_LUCKYTIME: 'ラッキータイム',
        FORTUNE_TAROT: 'タロット',
        FORTUNE_COLOR: '色占い',
        FORTUNE_NINESTAR: '九星',
        FORTUNE_CHART: '運勢グラフ',
        FORTUNE_FOURPILLARS: '四柱',
        FORTUNE_DREAM: '夢占い',

        // カートタブ
        CART_LIST: '📝 リスト',
        CART_CALC: '💰 計算',
        CART_HISTORY: '📋 履歴',

        // その他
        CALCULATE: '計算',
        RESULT: '結果',
        HISTORY: '履歴',
        EXPORT: 'エクスポート',
        IMPORT: 'インポート',
        DELETE: '削除',
        CLEAR_ALL: 'すべて削除',
        CLOSE: '閉じる',
        HELP: 'ヘルプ',
        BLOCKLY: '🧩 ブロック',

        // 日付計算の追加テキスト
        DATE_FIRST_DATE: '1つ目の日付',
        DATE_SECOND_DATE: '2つ目の日付',
        DATE_DIFFERENCE_CALC: '差分を計算',
        DATE_AGE_TITLE: '年齢・学年計算',
        DATE_BIRTH_DATE: '生年月日',
        DATE_CALC_AGE: '年齢を計算',
        DATE_RESULT: '結果',
        DATE_AGE_DETAILS: '年齢の詳細情報',
        DATE_YEAR: '年',
        DATE_MONTH: 'ヶ月',
        DATE_DAY: '日',
        DATE_YEAR_PROGRESS: '年の%経過',
        DATE_MONTH_PROGRESS: 'ヶ月の%経過',
        DATE_INFO_TITLE: '日付の情報',
        DATE_INFO_DATE: '日付',
        DATE_INFO_SEARCH: '情報を調べる',
        DATE_INFO_RESULT: '情報',
        DATE_ANNIVERSARY_TITLE: '記念日までの日数',
        DATE_ANNIVERSARY_DATE: '記念日の日付',
        DATE_ANNIVERSARY_CALC: '記念日までの日数を計算',
        DATE_ANNIVERSARY_NAME: '記念日の名前',
        DATE_ANNIVERSARY_TYPE: '種類',
        DATE_ANNIVERSARY_BIRTHDAY: '誕生日',
        DATE_ANNIVERSARY_ANNIVERSARY: '記念日',
        DATE_ANNIVERSARY_EVENT: 'イベント',
        DATE_ANNIVERSARY_CUSTOM: 'カスタム',
        DATE_ANNIVERSARY_REGISTER: '登録する',
        DATE_ANNIVERSARY_REGISTER_TITLE: '記念日を登録',
        DATE_ANNIVERSARY_NAME_LABEL: '名前',
        DATE_ANNIVERSARY_LIST_TITLE: '記念日リスト',
        DATE_ANNIVERSARY_CLEAR_ALL: 'すべて削除',
        DATE_ANNIVERSARY_EMPTY: '記念日はまだありません',
        DATE_HISTORY_EMPTY: '履歴がありません',
        DATE_ANNIVERSARY_DAYS_UNTIL: 'あと %日',
        DATE_ANNIVERSARY_TODAY: '今日です！',
        DATE_ANNIVERSARY_DAYS_PAST: '%日過ぎました',
        DATE_IMPORT_CSV: 'CSVからインポート',
        DATE_IMPORT_JSON: 'JSONからインポート',
        DATE_IMPORT_SUCCESS: '%件の記念日をインポートしました',
        DATE_IMPORT_ERROR: 'インポートに失敗しました: %',
        DATE_HISTORY_IMPORT_SUCCESS: '%件の履歴をインポートしました',

        // 単位変換の追加テキスト
        UNIT_CATEGORY_LENGTH: '長さ',
        UNIT_CATEGORY_WEIGHT: '重さ',
        UNIT_CATEGORY_VOLUME: '体積',
        UNIT_CATEGORY_TIME: '時間',
        UNIT_CATEGORY_TEMPERATURE: '温度',
        UNIT_CATEGORY_CURRENCY: '通貨',
        UNIT_NUMBER: '数値',

        // 十二支の追加テキスト
        ZODIAC_YEARS_PEOPLE: '%年生まれの人',
        ZODIAC_CURRENT_AGE: '→ 現在 %歳',

        // カートの追加テキスト
        CART_ITEMS: 'カートのアイテム',
        CART_ADD_ITEM_PROMPT: 'カートにアイテムを追加してください',
        CART_HISTORY_TITLE: 'カートの履歴',
        CART_HISTORY_EMPTY: '履歴がありません',
        CART_SUBTOTAL: '小計',
        CART_DISCOUNT: '割引',
        CART_TAX: '消費税',
        CART_TAX_RATE: '消費税率',
        CART_SETTINGS: '計算設定',
        CART_TOTAL: '合計',
        CART_ADD: '追加',
        CART_QUANTITY: '数量',

        // ウェルカムメッセージ
        WELCOME_TITLE: '計算ノートへようこそ！',
        WELCOME_DESC1: '左の電卓で、計算してみましょう',
        WELCOME_DESC2: '結果がマグネットになって、こちらに表示されます！',

        // 日付単位
        DATE_UNIT_DAYS_TEXT: '日',
        DATE_UNIT_WEEKS_TEXT: '週',
        DATE_UNIT_MONTHS_TEXT: '月',
        DATE_UNIT_YEARS_TEXT: '年',
        DATE_AGE_YEARS: '歳',
        DATE_AGE_MONTHS: 'ヶ月',
        DATE_AGE_DAYS: '日',
        DATE_AGE_TOTAL: '合計',
        DATE_BORN: '生まれ',
        DATE_NOW: '現在',

        // 日付計算結果
        DATE_EVENT_DAYS_UNTIL: 'イベントまでの日数',
        DATE_WEEK_POSITION: '週の何日目か',

        // エラーメッセージ
        ERROR_INVALID_YEAR: '正しい年を入力してください',
        ERROR_INVALID_YEAR_RANGE: '1から9999の年を入力してください',
        ERROR_INVALID_AGE: '0から125の年齢を入力してください',
        ERROR_INVALID_DATE: '正しい日付を入力してください',
        ERROR_INVALID_NUMBER: '正しい数値を入力してください',
        ERROR_QUIZ_WRONG: '残念！もう一度チャレンジ！',
        ERROR_NAME_DATE_REQUIRED: '名前と日付を入力してください',

        // Canvas
        CANVAS_SELECTED: '個のマグネットを選択中',
        CANVAS_GROUP: 'グループ化',
        CANVAS_UNGROUP: 'グループ解除',
        CANVAS_DELETE: '削除',
        CANVAS_SELECT_ALL: 'すべて',

        // CBlock
        CBLOCK_MEMO_WRITE: 'メモを書く',
        CBLOCK_DELETE: 'マグネットを削除',
        CBLOCK_DELETE_CONFIRM: 'このマグネットを削除しますか？',
        CBLOCK_MEMO_PLACEHOLDER: 'メモを書いてください (Ctrl+Enterで保存、Escでキャンセル)',
    },
} as const;

/**
 * テーマに応じたテキストを取得
 */
export function getThemeText(theme: Theme, key: keyof typeof TEXT_MAPPING.kids): string {
    return TEXT_MAPPING[theme][key] || TEXT_MAPPING.kids[key];
}

/**
 * 現在のテーマに応じたテキストを取得（React用）
 */
export function useThemeText(theme: Theme | null | undefined) {
    const currentTheme: Theme = theme || 'kids';
    return (key: keyof typeof TEXT_MAPPING.kids): string => {
        return getThemeText(currentTheme, key);
    };
}
